name: No legacy imports

on:
  pull_request:
  push:
    branches:
      - main
      - 'feat/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run legacy import check
        run: |
          python scripts/check_no_legacy_imports.py

